server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:nhood-location
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin