# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/openjdk:10-jdk

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout

    - run:
          name: Maven install
          command: |
            mvn clean install

    - run:
          name: Deploy to GitHub repository
          command: |
            mvn -s .circleci.settings.xml deploy

#    - run:
#          name: Deploy to Heroku
#          command: |
#            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/nhood-data-url-svc.git master
